### ISSUE TITLE
Support for Laravel 8

### ISSUE THREAD

**Issue by timdorey** [cerbero90/laravel-enum#4]
Will this package have support for Laravel 8 which was released on September 8 2020?

**Comment by cerbero90** [comment]
Hi @timdorey, Laravel 8 is now supported in the version `1.3.0` of this package 👍

**Comment by chrisk-7777** [comment]
Just a heads up I don't believe this is actually solved. 

You will need: `"php": "^7.1 || ^8.0",`in your composer.json
I started a fork, and was about to raise a PR, but unfortunately the underlying enum lib from `rexlabsio` is set to `^7.0`

**Comment by cerbero90** [comment]
Hi @chrisk-7777 

> Just a heads up I don't believe this is actually solved.

Partially true, it works on Laravel 8 if you are using PHP 7.3 or 7.4.

> I started a fork, and was about to raise a PR, but unfortunately the underlying enum lib from rexlabsio is set to ^7.0

Thank you for your help, you are right and that is unfortunate. Meanwhile if you need a valid enum package working with PHP 8, I'd recommend [Ben Sampson's Laravel Enum](https://github.com/BenSampo/laravel-enum) 👍

**Comment by cjke** [comment]
@cerbero90 I'm a dope, I read the title as "Support for **PHP** 8" - sorry!
