### ISSUE TITLE
PHP 8 support?

### ISSUE THREAD

**Issue by leganz** [cerbero90/laravel-enum#6]
Are there any plans to support php 8 ?

**Comment by cerbero90** [comment]
Hi @leganz and thanks for your interest.

The development of this package is interrupted for two main reasons:
1. there are more popular and complete alternatives, such as https://github.com/BenSampo/laravel-enum
2. PHP 8.1 will introduce enums in the PHP core itself: https://www.stitcher.io/blog/new-in-php-81

At the moment I'm busy with other work but if you really need this package to support PHP 8, please consider testing if updating the `composer.json` file is enough to support PHP 8 and feel free to send a PR in that case :)
